Module3 task1
htmlacademy-vue/570387-pizza-1 pull request #3
Opened 2023-08-11 12:44 UTC by AlehaWP

2023-08-14 12:13 UTC, S-le requested changes
Молодец! Большую часть работы ты выполнил. Осталось немного доработать. Проработай ещё раз [раздел 3.8](https://up.htmlacademy.ru/vue/1/module/3/item/8).

Пожалуйста, не меняй версии в зависимостях! Для работы над проектом уже все настроено. А изменения приводят к тому, что проект не запускается на машине наставника.

Доделывай работу и отправляй на проверку. Если есть вопросы, то можешь проконсультироваться.

2023-08-14 12:13 UTC, S-le commented on src/frontend/src/router/index.js
> +  // mode: 'history',
Можешь раскомментировать эту строчку. Роутер работает в режиме `history`. Если с эти какие-то проблемы, то напиши мне.

2023-08-14 12:13 UTC, S-le commented on src/frontend/src/router/index.js
> +      },
Страница __Login__ это отдельная страница. Она не зависит от __IndexHome__. Поэтому лучше сделать её корневым элементом массива `routes`.

2023-08-14 12:13 UTC, S-le commented on src/frontend/src/layouts/AppLayout.vue
> +      const layout = this.$route.meta.layout || defaultLayout;
Здесь проверяется `$route.meta.layout`, но в самих роутах они не прописаны.

2023-08-14 12:13 UTC, S-le commented on template/src/sass/blocks/input.scss
Файлы из папки `template` изменять не следует.

2023-08-15 22:10 UTC, AlehaWP commented on src/frontend/src/router/index.js
> +      },
Сделал

2023-08-15 22:49 UTC, AlehaWP commented on src/frontend/src/layouts/AppLayout.vue
> +      const layout = this.$route.meta.layout || defaultLayout;
Прописал пока один

2023-08-15 22:50 UTC, AlehaWP commented on template/src/sass/blocks/input.scss
Восстанавливал случайно измененный в прошлом PR

2023-08-15 22:50 UTC, AlehaWP commented on src/frontend/src/router/index.js
> +  // mode: 'history',
работает

2023-08-16 10:43 UTC, S-le commented on src/frontend/src/views/Index.vue
> +    <router-view />
`<router-view />` в компоненте `Index.vue` нужен в том случае, если в его роуте есть дочерние маршруты. Его стоило оставить если бы маршрут `/login` остался бы дочерним. Тут, наверное, я тебя смутил, когда порекомендовал переледать маршруты.

2023-08-16 10:43 UTC, S-le requested changes
Отлично! Я вижу, что хорошо разбираешься, давай только повнимательнее. Приступай к следующей теме.

2023-08-16 10:44 UTC, merged